pipeline {
    agent any
    
    environment{
        PATH= "/D:/Softwares/apache-maven-3.9.8/bin:$PATH"
    }

    stages {
        stage('clone') {
            steps {
                git url:'https://github.com/sarahjonna/simple-java-maven-app.git'
            }
        }
        stage('build') {
            steps {
                sh "mvn clean install"
            }
        }
    }
}
