pipeline {
    agent any
    stages{
        stage("SCM Checkout"){
            steps{
            git 'https://github.com/sarahjonna/simple-java-maven-app.git'
            }
        }
        stage("Maven Build"){
            steps{
                bat 'mvn clean package'
            }
        }
    }
}
